version: 3
services:
    ivideon-server:
        volumes:
            - '/home/bohdan/docker/ivideon-server/archive:/root/.IvideonServer/archive'
            - '/home/bohdan/docker/ivideon-server/videoserverd.config:/root/.IvideonServer/videoserverd.config'
        restart: always
        ports:
            - '6080:6080'
        container_name: ivideon-server
        image: ivideon-server
